<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Disable HTML asset fingerprint placeholders -->
    <OverrideHtmlAssetPlaceholders>false</OverrideHtmlAssetPlaceholders>
  </PropertyGroup>

  <ItemGroup>

    <!-- Blazor Storage -->
    <PackageReference Include="Blazor.Storage"
                      Version="5.0.0" />

    <!-- Excel -->
    <PackageReference Include="ClosedXML"
                      Version="0.105.1" />

    <!-- Authentication -->
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization"
                      Version="10.0.11" />

    <!-- Blazor WebAssembly -->
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly"
                      Version="10.0.10" />

    <!-- Blazor WebAssembly Development Server -->
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer"
                      Version="10.0.10"
                      PrivateAssets="all" />

    <!-- HTTP Client -->
    <PackageReference Include="Microsoft.Extensions.Http"
                      Version="10.0.11" />

    <!-- MudBlazor -->
    <PackageReference Include="MudBlazor"
                      Version="9.8.0" />

    <!-- Supabase -->
    <PackageReference Include="Supabase.Postgrest"
                      Version="4.4.0" />

  </ItemGroup>

</Project>
