using System;
using System.Collections.Generic;

namespace RubberTradingSystem.Services
{
    public enum Language { MM, EN }

    public class LanguageService
    {
        public Language CurrentLanguage { get; private set; } = Language.MM;
        public event Action? OnLanguageChanged;

        public void SetLanguage(Language lang)
        {
            CurrentLanguage = lang;
            OnLanguageChanged?.Invoke();
        }

        public string GetString(string key)
        {
            var dict = CurrentLanguage == Language.MM ? Myanmar : English;
            return dict.TryGetValue(key, out var val) ? val : $"[{key}]";
        }

        private static readonly Dictionary<string, string> English = new()
        {
            // --- Global & Menus ---
            { "AppName", "Rubber Trading ERP" },
            { "Dashboard", "Command Center" },
            { "Profile", "My Profile" },
            { "Logout", "Sign Out" },
            { "Search", "Search voucher or name..." },

            { "Menu_Trading", "Trading & Procurement" },
            { "Menu_Purchase", "Purchase Raw Rubber" },
            { "Menu_Sales", "Sales & Export RSS" },
            { "Menu_Vouchers", "Voucher History" },
            { "Menu_Pricing", "Daily Price Settings" },
            { "Menu_Production", "Production & Milling" },
            { "Menu_Milling", "Milling Process Log" },
            { "Menu_Shrinkage", "Shrinkage & Wastage" },
            { "Menu_WMS", "WMS & Inventory" },
            { "Menu_StockBal", "Stock Balance" },
            { "Menu_StockTransfer", "Stock Transfer" },
            { "Menu_StockAdj", "Stock Adjustment" },
            { "Menu_Finance", "Finance & Cashbook" },
            { "Menu_Expenses", "Daily Expenses" },
            { "Menu_Incomes", "Other Incomes" },
            { "Menu_Wallets", "Bank & Wallets Balance" },
            { "Menu_Transfers", "Fund Transfers" },
            { "Menu_Contacts", "Suppliers & Customers" },
            { "Menu_Suppliers", "Suppliers List" },
            { "Menu_Buyers", "Corporate Buyers" },
            { "Menu_Advances", "Advances & Loans" },
            { "Menu_Repayments", "Repayments & Auto-deduct" },
            { "Menu_Logistics", "Fleet & Logistics" },
            { "Menu_Vehicles", "Vehicle Master" },
            { "Menu_Fuel", "Fuel & Maintenance" },
            { "Menu_HR", "HR & Payroll" },
            { "Menu_Staff", "Staff Directory" },
            { "Menu_Attendance", "Attendance & Leave" },
            { "Menu_Payroll", "Payroll & Commission" },
            { "Menu_Assets", "Fixed Assets" },
            { "Menu_AssetList", "Assets List" },
            { "Menu_Depreciation", "Depreciation" },
            { "Menu_Reports", "Reports & Analytics" },
            { "Menu_PnL", "Profit & Loss" },
            { "Menu_Sync", "Manual Sync & Offline" },
            { "Menu_Push", "Review & Push Data" },
            { "Menu_Settings", "Advanced ERP Settings" },
            { "Menu_ThemeLang", "Theme & Language" },
            { "Menu_Defaults", "Business Defaults" },
            { "Menu_Print", "Print & Vouchers" },
            { "Menu_Roles", "Users & Roles (RBAC)" },
            { "Menu_Audit", "Audit Logs" },
            { "Menu_Backup", "Database Backup" },
            { "Menu_DataManagement", "Data Management" },
            { "Menu_RubberTypes", "Rubber Types" },
            { "Menu_PaymentMethods", "Payment Methods" },
            { "Menu_FarmAccounts", "Supplier Accounts" },
            { "Menu_BalanceSummary", "Receivables & Payables" },
            { "Menu_PurchaseList", "Purchase List" },
            { "Menu_BuyerAdvanceOut", "Received Advance From Buyer/Company" },
            { "Menu_BuyerAdvanceIn", "Repayment Advance To Buyer/Company" },
            { "Menu_WarehouseTransfer", "Warehouse Transfer" },
            { "Menu_StockBalance", "Stock Balance" },
            { "Menu_ExpenseManagement", "Expenses Management" },
            { "Menu_ExpenseList", "Daily Expenses" },
            { "Menu_ExpenseSettings", "Expense Settings" },
            { "Menu_FundTransfer", "Fund Transfer" },
            { "Menu_SmokingProcess", "Rubber Smoking Process" },
            { "Menu_SmokingAnalytics", "Smoking Analytics & Loss Report" },

            // --- Dashboard ---
            { "DashboardSubtitle", "Today is {0}. Here is your business overview." },
            { "OfflinePending", "Offline Mode ({0} Pending)" },
            { "TodayPurchaseWet", "Total Purchase Today (Wet)" },
            { "Pound", "lbs" },
            { "PurchaseIncrease", "15% higher than yesterday" },
            { "RSSProduction", "RSS Production" },
            { "Shrinkage", "Shrinkage 12%" },
            { "CashBankBalance", "Cash & Bank Balance" },
            { "Kyat", "MMK" },
            { "TotalKPayCash", "Total of KPay and Cash" },
            { "WarehouseStock", "Warehouse Rubber Stock" },
            { "TotalAllWarehouses", "Total in all warehouses" },
            { "WeeklyPurchaseTrend", "Weekly Purchase Trend (Wet/lbs)" },
            { "QuickActions", "Quick Actions" },
            { "BuyWetRubber", "Buy Wet Rubber" },
            { "RecordExpense", "Record Expense" },
            { "AddNewSupplier", "Add New Supplier" },
            { "ManualSyncBtn", "Manual Sync" },
            { "RecentTransactions", "Recent Transactions" },

            // --- Common/General ---
            { "Voucher", "Voucher" },
            { "NameDescription", "Name/Description" },
            { "Amount", "Amount" },
            { "Status", "Status" },
            { "Cleared", "Cleared" },
            { "Pending", "Pending" },
            { "ClearedKpay", "Cleared (KPay)" },
            { "Alerts", "Alerts" },
            { "AdvancePaymentAlert", "Advance payment to U Mya has exceeded 1 month." },
            { "LowStockAlert", "RSS stock in Warehouse (A) is below the minimum threshold." },
            { "Cancel", "Cancel" },
            { "Creating", "Creating..." },
            { "Create", "Create Account" },
            { "GeneralError", "Error: " },
            { "Btn_AddNew", "Add New" },
            { "Btn_Edit", "Edit" },
            { "Btn_Delete", "Delete" },
            { "Btn_Add", "Add New" },
            { "Btn_YesDelete", "Yes, Delete" },
            { "Btn_Cancel", "Cancel" },
            { "Btn_Back", "Back" },
            { "Btn_Saving", "Saving..." },
            { "Btn_Save", "Save" },
            { "Btn_SaveChanges", "Save Changes" },
            { "Btn_Yes", "Yes" },
            { "Msg_Warning", "Warning" },
            { "Msg_DeleteConfirm", "Are you sure you want to delete the record of {0}?" },
            { "Msg_DelSuccess", "Record deleted successfully." },
            { "Msg_DelError", "Error deleting record." },
            { "Msg_NetError", "Network error: " },
            { "Msg_LoadError", "Error loading data: " },
            { "Msg_Success", "Advance payment successful!" },
            { "Msg_Error", "Error: " },
            { "Msg_NotFound", "Contact not found." },
            { "Msg_UpdateSuccess", "Contact updated successfully." },
            { "Confirm_Title", "Confirmation" },
            { "Confirm_DeleteMessage", "Are you sure you want to delete this item?" },

            // --- Staff Management ---
            { "Staff_AddNew", "Create New Staff Account" },
            { "Staff_Name", "Staff Name" },
            { "Staff_Email", "Email Address" },
            { "Staff_Password", "Password" },
            { "Staff_CreateSuccess", "Staff account created successfully." },
            { "Staff_CreateError", "Failed to create staff account: " },
            { "Staff_ListTitle", "Staff Accounts List" },
            { "Staff_SearchPlaceholder", "Search by name or email..." },
            { "Staff_TableColName", "Staff Name" },
            { "Staff_TableColEmail", "Email Address" },
            { "Staff_TableColRole", "Role / Status" },
            { "Staff_DeleteConfirm", "Are you sure you want to delete the account for " },
            { "Staff_DeleteSuccess", "Staff account deleted successfully." },
            { "Staff_DeleteError", "Failed to delete staff account." },
            { "Staff_LoadError", "Failed to load staff accounts: " },

            // --- Payment Methods ---
            { "Payment_ListTitle", "Payment Methods Management" },
            { "Payment_SearchPlaceholder", "Search payment method..." },
            { "Payment_ColName", "Payment Method Name" },
            { "Payment_ColType", "Type / Provider" },
            { "Payment_ColDetails", "Account Details / Number" },
            { "Payment_ColStatus", "Status" },
            { "Payment_StatusActive", "Active" },
            { "Payment_StatusInactive", "Inactive" },
            { "Payment_AddTitle", "Add Payment Method" },
            { "Payment_EditTitle", "Edit Payment Method" },
            { "Payment_NameLabel", "Method Name (e.g. KBZ Pay)" },
            { "Payment_TypeLabel", "Type (e.g. Mobile Wallet / Bank)" },
            { "Payment_DetailsLabel", "Account Name & Number" },
            { "Payment_SaveSuccess", "Payment method saved successfully." },
            { "Payment_DeleteConfirm", "Are you sure you want to delete this payment method?" },

            // --- Rubber Types ---
            { "Rubber_ListTitle", "Rubber Types Management" },
            { "Rubber_SearchPlaceholder", "Search rubber type..." },
            { "Rubber_ColName", "Rubber Name" },
            { "Rubber_ColGrade", "Grade" },
            { "Rubber_ColDesc", "Description" },
            { "Rubber_AddTitle", "Add Rubber Type" },
            { "Rubber_EditTitle", "Edit Rubber Type" },
            { "Rubber_NameLabel", "Rubber Name (e.g. RSS-3)" },
            { "Rubber_GradeLabel", "Grade (e.g. Premium)" },
            { "Rubber_DescLabel", "Description" },
            { "Rubber_AddButton", "Add New" },
            { "Rubber_EditButton", "Edit" },
            { "Rubber_DeleteButton", "Delete" },
            { "Rubber_Cancel", "Cancel" },
            { "Rubber_Save", "Save" },
            { "Rubber_Update", "Update" },
            { "Rubber_SaveSuccess", "Rubber type saved successfully." },
            { "Rubber_UpdateSuccess", "Rubber type updated successfully." },
            { "Rubber_DeleteSuccess", "Rubber type deleted successfully." },
            { "Rubber_DeleteConfirm", "Are you sure you want to delete this rubber type?" },

            // --- Purchasing ---
            { "Purchase_ListTitle", "Rubber Purchasing Management" },
            { "Purchase_SearchPlaceholder", "Search supplier or rubber type..." },
            { "Purchase_ColSupplier", "Supplier Name" },
            { "Purchase_ColType", "Rubber Type" },
            { "Purchase_ColWeight", "Weight" },
            { "Purchase_ColPrice", "Price / Unit" },
            { "Purchase_ColTotal", "Total Amount" },
            { "Purchase_ColDate", "Date" },
            { "Purchase_AddButton", "New Purchase" },
            { "Purchase_EditButton", "Edit" },
            { "Purchase_AddTitle", "Add New Purchase" },
            { "Purchase_EditTitle", "Edit Purchase" },
            { "Purchase_SupplierLabel", "Supplier Name" },
            { "Purchase_TypeLabel", "Rubber Type" },
            { "Purchase_WeightLabel", "Weight" },
            { "Purchase_PriceLabel", "Price Per Unit" },
            { "Purchase_SaveSuccess", "Purchase record saved successfully." },
            { "Purchase_UpdateSuccess", "Purchase record updated successfully." },
            { "Purchase_DeleteSuccess", "Purchase record deleted successfully." },
            { "Purchase_DeleteConfirm", "Are you sure you want to delete this purchase record?" },

            // --- Pricing ---
            { "Price_ListTitle", "Daily Rubber Prices Management" },
            { "Price_SearchPlaceholder", "Search rubber type..." },
            { "Price_ColType", "Rubber Type" },
            { "Price_ColPrice", "Price per Unit" },
            { "Price_ColDate", "Effective Date" },
            { "Price_AddButton", "Set New Price" },
            { "Price_EditButton", "Edit Price" },
            { "Price_AddTitle", "Set Daily Price" },
            { "Price_EditTitle", "Edit Daily Price" },
            { "Price_TypeLabel", "Rubber Type" },
            { "Price_ValueLabel", "Price per Unit" },
            { "Price_DateLabel", "Effective Date" },
            { "Price_SaveSuccess", "Daily price saved successfully." },
            { "Price_UpdateSuccess", "Daily price updated successfully." },
            { "Price_DeleteSuccess", "Daily price deleted successfully." },
            { "Price_DeleteConfirm", "Are you sure you want to delete this price record?" },

            // --- Expenses & Incomes ---
            { "Expense_ListTitle", "Expenses List" },
            { "Expense_SearchPlaceholder", "Search by title or category..." },
            { "Expense_ColTitle", "Title" },
            { "Expense_ColCategory", "Category" },
            { "Expense_ColAmount", "Amount" },
            { "Expense_ColDate", "Date" },
            { "Expense_ColNote", "Note" },
            { "Expense_AddButton", "Add Expense" },
            { "Expense_EditButton", "Edit" },
            { "Expense_AddTitle", "Add New Expense" },
            { "Expense_EditTitle", "Edit Expense" },
            { "Expense_TitleLabel", "Title" },
            { "Expense_CategoryLabel", "Category" },
            { "Expense_AmountLabel", "Amount" },
            { "Expense_PaymentMethodLabel", "Payment Method" },
            { "Expense_SaveSuccess", "Expense saved successfully." },
            { "Expense_UpdateSuccess", "Expense updated successfully." },
            { "Expense_DeleteSuccess", "Expense deleted successfully." },
            { "Expense_DeleteConfirm", "Are you sure you want to delete this expense record?" },
            { "Expense_ColPaymentMethod", "Payment Method" },

            { "Income_ListTitle", "Other Incomes Management" },
            { "Income_SearchPlaceholder", "Search description..." },
            { "Income_ColDesc", "Description" },
            { "Income_ColAmount", "Amount" },
            { "Income_ColDate", "Date" },
            { "Income_ColNote", "Note" },
            { "Income_AddButton", "Add Income" },
            { "Income_EditButton", "Edit Income" },
            { "Income_AddTitle", "Add New Income" },
            { "Income_EditTitle", "Edit Income" },
            { "Income_DescLabel", "Description" },
            { "Income_AmountLabel", "Amount" },
            { "Income_NoteLabel", "Note (Optional)" },
            { "Income_SaveSuccess", "Income saved successfully." },
            { "Income_UpdateSuccess", "Income updated successfully." },
            { "Income_DeleteSuccess", "Income deleted successfully." },
            { "Income_DeleteConfirm", "Are you sure you want to delete this income record?" },
            { "Income_ColPaymentMethod", "Payment Method" },
            { "Income_PaymentMethodLabel", "Payment Method" },
            { "Income_Cash", "Cash" },

            // --- Expense Settings ---
            { "ExpSetting_Title", "Expense Categories & Titles Setup" },
            { "ExpSetting_TabCategory", "Categories" },
            { "ExpSetting_TabTitle", "Titles" },
            { "ExpSetting_NameLabel", "Name (e.g. Daily Expense, Food)" },
            { "ExpSetting_AddBtn", "Add New" },
            { "ExpSetting_SaveSuccess", "Successfully saved." },
            { "ExpSetting_DeleteSuccess", "Successfully deleted." },
            { "ExpSetting_TypeLabel", "Type" },
            { "ExpSetting_CategoryOpt", "Category" },
            { "ExpSetting_TitleOpt", "Title" },
            { "ExpSetting_ParentCategoryLabel", "Select Parent Category" },
            { "ExpSetting_SearchPlaceholder", "Search by name..." },
            { "ExpSetting_ColType", "Type" },
            { "ExpSetting_ColName", "Name" },
            { "ExpSetting_ColParentCategory", "Parent Category" },

            // --- Logistics (Trucks & Expenses) ---
            { "Truck_ListTitle", "Truck Management" },
            { "Truck_SearchPlaceholder", "Search truck number or driver..." },
            { "Truck_ColNumber", "Truck Number" },
            { "Truck_ColDriver", "Driver Name" },
            { "Truck_ColStatus", "Status" },
            { "Truck_ColCapacity", "Capacity (kg)" },
            { "Truck_AddButton", "Add Truck" },
            { "Truck_EditButton", "Edit Truck" },
            { "Truck_AddTitle", "Add New Truck" },
            { "Truck_EditTitle", "Edit Truck" },
            { "Truck_NumberLabel", "Truck Number (e.g. 8A-1234)" },
            { "Truck_DriverLabel", "Driver Name" },
            { "Truck_StatusLabel", "Status" },
            { "Truck_CapacityLabel", "Capacity (kg)" },
            { "Truck_SaveSuccess", "Truck saved successfully." },
            { "Truck_UpdateSuccess", "Truck updated successfully." },
            { "Truck_DeleteSuccess", "Truck deleted successfully." },
            { "Truck_DeleteConfirm", "Are you sure you want to delete this truck record?" },

            { "TruckExp_ListTitle", "Truck Fuel & Maintenance Expenses" },
            { "TruckExp_SearchPlaceholder", "Search truck or expense type..." },
            { "TruckExp_ColTruck", "Truck Number" },
            { "TruckExp_ColType", "Expense Type" },
            { "TruckExp_ColAmount", "Amount" },
            { "TruckExp_ColPayment", "Payment Method" },
            { "TruckExp_ColDate", "Date" },
            { "TruckExp_ColNote", "Note" },
            { "TruckExp_AddButton", "Add Expense" },
            { "TruckExp_EditButton", "Edit Expense" },
            { "TruckExp_AddTitle", "Add Truck Expense" },
            { "TruckExp_EditTitle", "Edit Truck Expense" },
            { "TruckExp_TruckLabel", "Truck Number" },
            { "TruckExp_TypeLabel", "Expense Type (Fuel / Maintenance)" },
            { "TruckExp_Fuel", "Fuel" },
            { "TruckExp_Maintenance", "Maintenance" },
            { "TruckExp_SaveSuccess", "Truck expense saved successfully." },
            { "TruckExp_UpdateSuccess", "Truck expense updated successfully." },
            { "TruckExp_DeleteSuccess", "Truck expense deleted successfully." },
            { "TruckExp_DeleteConfirm", "Are you sure you want to delete this expense record?" },

            // --- Employee Management ---
            { "Emp_ListTitle", "Employee Management" },
            { "Emp_SearchPlaceholder", "Search employee name or position..." },
            { "Emp_ColName", "Full Name" },
            { "Emp_ColPosition", "Position" },
            { "Emp_ColSalary", "Salary" },
            { "Emp_ColPhone", "Phone" },
            { "Emp_AddButton", "Add Employee" },
            { "Emp_EditButton", "Edit Employee" },
            { "Emp_AddTitle", "Add New Employee" },
            { "Emp_EditTitle", "Edit Employee" },
            { "Emp_NameLabel", "Full Name" },
            { "Emp_PositionLabel", "Position" },
            { "Emp_SalaryLabel", "Salary" },
            { "Emp_PhoneLabel", "Phone Number" },
            { "Emp_AddressLabel", "Address" },
            { "Emp_DateLabel", "Hire Date" },
            { "Emp_StatusLabel", "Status" },
            { "Emp_Profile", "Profile" },
            { "Emp_SaveSuccess", "Employee saved successfully." },
            { "Emp_UpdateSuccess", "Employee updated successfully." },
            { "Emp_DeleteSuccess", "Employee deleted successfully." },
            { "Emp_DeleteConfirm", "Are you sure you want to delete this employee record?" },

            // --- Warehouse Management ---
            { "Wh_ListTitle", "Warehouse Management" },
            { "Wh_SearchPlaceholder", "Search warehouse name or location..." },
            { "Wh_ColName", "Warehouse Name" },
            { "Wh_ColLocation", "Location" },
            { "Wh_ColManager", "Manager" },
            { "Wh_ColPhone", "Phone" },
            { "Wh_ColCapacity", "Capacity / Desc" },
            { "Wh_AddButton", "Add Warehouse" },
            { "Wh_EditButton", "Edit Warehouse" },
            { "Wh_AddTitle", "Add New Warehouse" },
            { "Wh_EditTitle", "Edit Warehouse" },
            { "Wh_NameLabel", "Warehouse Name" },
            { "Wh_LocationLabel", "Location / Address" },
            { "Wh_ManagerLabel", "Manager Name" },
            { "Wh_PhoneLabel", "Phone Number" },
            { "Wh_CapacityLabel", "Capacity / Description" },
            { "Wh_SaveSuccess", "Warehouse saved successfully." },
            { "Wh_UpdateSuccess", "Warehouse updated successfully." },
            { "Wh_DeleteSuccess", "Warehouse deleted successfully." },
            { "Wh_DeleteConfirm", "Are you sure you want to delete this warehouse record?" },

            // --- Daily Notes ---
            { "Note_ListTitle", "Daily Notes & Activities" },
            { "Note_SearchPlaceholder", "Search note title or content..." },
            { "Note_ColTitle", "Title" },
            { "Note_ColContent", "Content" },
            { "Note_ColDate", "Date" },
            { "Note_AddButton", "Add Note" },
            { "Note_EditButton", "Edit Note" },
            { "Note_AddTitle", "Add New Note" },
            { "Note_EditTitle", "Edit Note" },
            { "Note_TitleLabel", "Note Title" },
            { "Note_ContentLabel", "Content / Details" },
            { "Note_DateLabel", "Date" },
            { "Note_SaveSuccess", "Note saved successfully." },
            { "Note_UpdateSuccess", "Note updated successfully." },
            { "Note_DeleteSuccess", "Note deleted successfully." },
            { "Note_DeleteConfirm", "Are you sure you want to delete this note?" },

            // --- Rubber Sales ---
            { "Sale_ListTitle", "Rubber Sales List" },
            { "Sale_ColVoucher", "Voucher No" },
            { "Sale_ColBuyer", "Buyer / Company" },
            { "Sale_ColWarehouse", "Warehouse" },
            { "Sale_ColType", "Rubber Type" },
            { "Sale_ColWeight", "Weight" },
            { "Sale_ColPrice", "Price" },
            { "Sale_ColTotal", "Total Amount" },
            { "Sale_ColPayment", "Payment Method" },
            { "Sale_ColDate", "Date" },
            { "Sale_ColNote", "Note" },
            { "Sale_AddButton", "New Sale" },
            { "Sale_EditButton", "Edit Sale" },
            { "Sale_DeleteButton", "Delete Sale" },
            { "Sale_AddTitle", "Create Rubber Sale Invoice" },
            { "Sale_EditTitle", "Edit Rubber Sale Invoice" },
            { "Sale_InvoiceLabel", "Invoice Number" },
            { "Sale_CustomerLabel", "Customer Name" },
            { "Sale_WarehouseLabel", "Warehouse Source" },
            { "Sale_TypeLabel", "Rubber Type" },
            { "Sale_WeightLabel", "Weight (kg)" },
            { "Sale_PriceLabel", "Price per kg" },
            { "Sale_TotalLabel", "Total Amount (MMK)" },
            { "Sale_SaveSuccess", "Rubber sale saved successfully." },
            { "Sale_UpdateSuccess", "Rubber sale updated successfully." },
            { "Sale_DeleteSuccess", "Sale deleted successfully." },
            { "Sale_DeleteConfirm", "Are you sure you want to delete this sale?" },
            { "Sale_Title", "Rubber Sales Voucher" },
            { "Sale_SourceType", "Source Type" },
            { "Sale_SelectSource", "Select Stock Source" },
            { "Sale_AvailableQty", "Available Quantity" },
            { "Sale_Buyer", "Select Buyer" },
            { "Sale_ActualPaid", "Actual Received Amount" },
            { "Sale_Wallet", "Payment Wallet" },
            { "Sale_SaveButton", "Confirm Sale" },
            { "Sale_QtyWarningTitle", "Quantity Exceeded" },
            { "Sale_QtyWarningMsg", "The entered weight exceeds the currently available quantity. Are you sure you want to proceed?" },
            { "Sale_SearchPlaceholder", "Search by voucher, buyer..." },

            // --- Reports, Stocks & Processing ---
            { "Report_Title", "Financial Summary Report" },
            { "Report_Generate", "Generate Report" },
            { "Stock_Title", "Warehouse Stock Balance" },
            { "Stock_ColWarehouse", "Warehouse" },
            { "Stock_ColType", "Rubber Type" },
            { "Stock_ColBalance", "Stock Balance (kg)" },

            { "Smoking_Title", "Rubber Smoking Process" },
            { "Smoking_NewBatch", "New Smoking Batch" },
            { "Smoking_BatchNo", "Batch No" },
            { "Smoking_Status", "Status" },
            { "Smoking_Warehouse", "Warehouse" },
            { "Smoking_Input", "Input (Type / Qty)" },
            { "Smoking_Output", "Output (Type / Qty)" },
            { "Smoking_Shrinkage", "Shrinkage Loss" },
            { "Smoking_Dates", "Dates" },

            // --- Accounts & Contacts ---
            { "Accounts_Title", "Supplier Accounts" },
            { "Supplier_Name", "Supplier Name" },
            { "Total_Purchased", "Total Purchased" },
            { "Total_Paid", "Total Paid" },
            { "Balance_Due", "Balance Due" },
            { "Amount_Paid", "Amount Paid" },
            { "Payment_Method", "Method" },
            { "Cash", "Cash" },
            { "Bank_Transfer", "Bank Transfer" },
            { "ContactsTitle", "Suppliers & Customers List" },
            { "SearchContact", "Search by name or phone..." },
            { "Col_Name", "Name" },
            { "Col_Phone", "Phone Number" },
            { "Col_Type", "Contact Type" },
            { "Col_Advance", "Advance/Credit Balance" },

            { "Title_AddContact", "Add New Contact" },
            { "Lbl_Name", "Name / Company Name" },
            { "Err_NameRequired", "Name is required" },
            { "Lbl_Phone", "Phone Number" },
            { "Lbl_ContactType", "Contact Type" },
            { "Opt_Supplier", "Supplier / Broker" },
            { "Opt_Buyer", "Buyer / Merchant" },
            { "Opt_General", "General" },
            { "Lbl_BankInfo", "Bank / KPay Info" },
            { "Lbl_Address", "Address" },
            { "Title_EditContact", "Edit Contact" },
            { "Filter_All", "All Contacts" },
            { "Filter_Suppliers", "Suppliers / Brokers" },
            { "Filter_Buyers", "Buyers / Merchants" },
            { "Filter_General", "General" },
            { "Title_AdvanceOut", "Supplier Advance Payment" },
            { "Lbl_SelectSupplier", "Select Supplier" },
            { "Lbl_Amount", "Amount" },
            { "Lbl_Note", "Note" },
            { "Btn_PayAdvance", "Pay Advance" },
            { "Title_AdvanceIn", "Receive Advance from Farm Owner" },
            { "Lbl_CurrentAdvance", "Current Advance" },
            { "Lbl_SelectWallet", "Select Wallet / Payment Account" },
            { "Btn_ReceiveAdvance", "Receive Advance" },
            { "Msg_WalletUpdateError", "Failed to update wallet balance: " },
            { "Title_BalanceSummary", "Receivables & Payables Summary" },
            { "Card_TotalAdvanceOut", "Total Advance Given (Payable/Advance)" },
            { "Card_TotalReceivable", "Total Receivable Balance" },
            { "Tab_Suppliers", "Farm Owners (Suppliers)" },
            { "Tab_Buyers", "Merchants (Buyers)" },
            { "Tab_AllContacts", "All Contacts" },
            { "Placeholder_Search", "Search by name or phone..." },
            { "Th_Name", "Name" },
            { "Th_Phone", "Phone" },
            { "Th_Type", "Type" },
            { "Th_AdvanceBalance", "Advance Balance" },
            { "Th_ReceivableBalance", "Receivable Balance" },

            // --- Settings & Buying ---
            { "Settings_Title", "Business Settings & Defaults" },
            { "Settings_WeightUnit", "Default Weight Unit" },
            { "Settings_ServiceCost", "Default Service Cost" },
            { "Settings_Deduction", "Default Deduction (%)" },
            { "Settings_Currency", "Currency Symbol" },
            { "Settings_AutoAdvance", "Enable Auto Advance Deduction" },
            { "Settings_SaveSuccess", "Settings saved successfully." },
            { "Settings_SaveButton", "Save Changes" },
            { "Settings_UpdateButton", "Update Changes" },
            { "Settings_DeleteButton", "Delete" },
            { "Settings_DeleteConfirm", "Are you sure you want to delete these settings?" },
            { "Settings_DeleteSuccess", "Settings deleted successfully." },

            { "Buy_Title", "Rubber Purchase Transaction" },
            { "Buy_Farmer", "Farmer / Supplier" },
            { "Buy_RubberType", "Rubber Type" },
            { "Buy_BasePrice", "Base Price" },
            { "Buy_ServiceCost", "Service Cost" },
            { "Buy_DeductionPct", "Deduction % (0-30)" },
            { "Buy_FinalPrice", "Agreed Price per Unit" },
            { "Buy_Weight", "Weight" },
            { "Buy_TotalAmount", "Total Amount" },
            { "Buy_Advance", "Advance Balance" },
            { "Buy_NetPayable", "Net Payable" },
            { "Buy_ActualPaid", "Actual Paid Amount" },
            { "Buy_SaveSuccess", "Rubber purchase saved successfully." },
            { "Buy_SaveButton", "Confirm Purchase" },

            { "Title_WarehouseTransfer", "Warehouse Batch Transfer" },
            { "Lbl_SelectWarehouse", "Select Warehouse" },
            { "Btn_TransferToWarehouse", "Transfer to Warehouse" },
            { "Msg_TransferSuccess", "Stock transferred to warehouse successfully." },
            { "Msg_SelectStockWarning", "Please select stocks to transfer." },

            { "Title_StockBalance", "Stock Balance Summary" },
            { "Tab_Warehouse", "Warehouse Stocks" },
            { "Tab_TempStock", "Temp Stocks (Pending)" },
            { "Tab_TruckStock", "Truck Stocks (Active)" },
            { "Th_WarehouseName", "Warehouse Name" },
            { "Th_Supplier", "Supplier" },
            { "Th_TruckNumber", "Truck Number" },
            { "Th_RubberType", "Rubber Type" },
            { "Th_Quantity", "Quantity / Weight" },

            { "Transfer_ListTitle", "Fund Transfers History" },
            { "Transfer_SearchPlaceholder", "Search by account name..." },
            { "Transfer_ColFrom", "From Account" },
            { "Transfer_ColTo", "To Account" },
            { "Transfer_ColAmount", "Amount" },
            { "Transfer_ColDate", "Date" },
            { "Transfer_ColNote", "Note" },
            { "Transfer_AddButton", "New Transfer" },
            { "Transfer_DeleteButton", "Delete" },
            { "Transfer_AddTitle", "Transfer Funds Between Accounts" },
            { "Transfer_DeleteSuccess", "Transfer record deleted successfully." },
            { "Transfer_FromLabel", "From Account (Source)" },
            { "Transfer_ToLabel", "To Account (Destination)" },
            { "Transfer_AmountLabel", "Transfer Amount" },
            { "Transfer_DateLabel", "Date" },
            { "Transfer_NoteLabel", "Note" },
            { "Transfer_SaveSuccess", "Funds transferred successfully." },
            { "Transfer_SameWalletError", "Source and destination accounts cannot be the same." },
            { "Transfer_InsufficientBalance", "Insufficient balance in the source account." },

            { "Smoking_ListTitle", "Rubber Smoking Batches" },
            { "Smoking_SearchPlaceholder", "Search by batch number..." },
            { "Smoking_ColBatchNo", "Batch Number" },
            { "Smoking_ColStartDate", "Start Date" },
            { "Smoking_ColEndDate", "End Date" },
            { "Smoking_ColStatus", "Status" },
            { "Smoking_ColInput", "Total Input (lbs)" },
            { "Smoking_ColOutput", "Total Output (lbs)" },
            { "Smoking_ColLoss", "Loss Weight" },
            { "Smoking_AddButton", "New Smoking Batch" },
            { "Smoking_CompleteButton", "Complete Batch" },
            { "Smoking_AddTitle", "Create Rubber Smoking Batch" },
            { "Smoking_CompleteTitle", "Smoking Completion & Grading (Complete Batch)" },
            { "Smoking_SupplierLabel", "Supplier / Farmer" },
            { "Smoking_InputWeightLabel", "Input Weight (lbs)" },
            { "Smoking_OutputWeightLabel", "Finished Output Weight (lbs)" },
            { "Smoking_SaveSuccess", "Smoking batch created successfully." },
            { "Smoking_CompleteSuccess", "Smoking batch completed and inventory updated." },
            { "Th_Source", "Source / ရင်းမြစ်" },
            { "Th_SupplierOrVehicle", "Supplier / Vehicle" },
            { "Th_Weight", "Weight" },
            { "Th_Moisture", "Moisture %" },
            { "Smoking_TargetWarehouse", "Select Finished Goods Warehouse" },
            { "Smoking_ItemAllocationTitle", "Batch Output, Grade, Remaining & Loss Weights" },
            { "Smoking_GradeLabel", "Rubber Grade" },
            { "Smoking_RemainingLabel", "Remaining Weight for Re-smoke" },
            { "Title_SmokingAnalytics", "Smoking Analytics & Loss Report" },
            { "Card_TotalInput", "Total Input Weight" },
            { "Card_TotalOutput", "Total Output Weight" },
            { "Card_TotalLoss", "Total Loss Weight" },
            { "Card_AvgMoisture", "Average Moisture" },
            { "Th_BatchNo", "Batch Number" },
            { "Th_StartDate", "Start Date" },
            { "Th_EndDate", "End Date" },
            { "Th_InputWeight", "Input (lbs)" },
            { "Th_OutputWeight", "Output (lbs)" },
            { "Th_LossWeight", "Loss (lbs)" },
            { "Th_LossPercent", "Loss %" },
            { "Th_MoisturePercent", "Moisture %" }
        };

        private static readonly Dictionary<string, string> Myanmar = new()
        {
            // --- Global & Menus ---
            { "AppName", "ရော်ဘာအရောင်းအဝယ် ERP" },
            { "Dashboard", "ပင်မ ထိန်းချုပ်ခန်း" },
            { "Profile", "ကိုယ်ရေးအချက်အလက်" },
            { "Logout", "အကောင့်ထွက်ရန် (Logout)" },
            { "Search", "ဘောက်ချာ (သို့) အမည် ရှာရန်..." },

            { "Menu_Trading", "အရောင်းအဝယ် ကဏ္ဍ" },
            { "Menu_Purchase", "ရော်ဘာအစို ဝယ်ယူရန်" },
            { "Menu_Sales", "မှိုင်းခံပြား (RSS) ရောင်းရန်" },
            { "Menu_Vouchers", "ဘောက်ချာ မှတ်တမ်းများ" },
            { "Menu_Pricing", "နေ့စဉ်ပေါက်ဈေး သတ်မှတ်ရန်" },
            { "Menu_Production", "စက်ရုံနှင့် ကုန်ထုတ်လုပ်မှု" },
            { "Menu_Milling", "မှိုင်းခံ/ကြိတ်ခွဲမှု စာရင်း" },
            { "Menu_Shrinkage", "အလေးချိန် လျော့ကျမှု" },
            { "Menu_WMS", "ဂိုဒေါင် ကုန်လက်ကျန်" },
            { "Menu_StockBal", "ဂိုဒေါင်အလိုက် လက်ကျန်" },
            { "Menu_StockTransfer", "ဂိုဒေါင် ကုန်ရွှေ့ပြောင်းခြင်း" },
            { "Menu_StockAdj", "ကုန်လက်ကျန် စာရင်းညှိခြင်း" },
            { "Menu_Finance", "ငွေစာရင်းနှင့် နေ့စဉ်စာအုပ်" },
            { "Menu_Expenses", "နေ့စဉ် အသုံးစရိတ်များ" },
            { "Menu_Incomes", "အခြား ဝင်ငွေများ" },
            { "Menu_Wallets", "ဘဏ်နှင့် လက်ကျန်ငွေများ" },
            { "Menu_Transfers", "အကောင့် ငွေလွှဲပြောင်းမှု" },
            { "Menu_Contacts", "ခြံရှင်/ကုန်သည် စာရင်း" },
            { "Menu_Suppliers", "ခြံရှင်/ရောင်းချသူများ" },
            { "Menu_Buyers", "ဝယ်ယူသည့် ကုမ္ပဏီများ" },
            { "Menu_Advances", "ကြိုတင်ငွေ ထုတ်ယူမှုများ" },
            { "Menu_Repayments", "အကြွေးပြန်ဆပ်/ဖြတ်တောက်မှု" },
            { "Menu_Logistics", "သယ်ယူပို့ဆောင်ရေး" },
            { "Menu_Vehicles", "ကုန်တင်ကား စာရင်း" },
            { "Menu_Fuel", "ဆီဖိုးနှင့် ပြုပြင်စရိတ်" },
            { "Menu_HR", "ဝန်ထမ်းရေးရာနှင့် လစာ" },
            { "Menu_Staff", "ဝန်ထမ်း အချက်အလက်များ" },
            { "Menu_Attendance", "တက်/ပျက် မှတ်တမ်း" },
            { "Menu_Payroll", "လစာနှင့် ကော်မရှင်" },
            { "Menu_Assets", "လုပ်ငန်းပိုင် ပစ္စည်းများ" },
            { "Menu_AssetList", "ပိုင်ဆိုင်မှု စာရင်း" },
            { "Menu_Depreciation", "တန်ဖိုးလျော့ တွက်ချက်မှု" },
            { "Menu_Reports", "အစီရင်ခံစာများ" },
            { "Menu_PnL", "အရှုံးအမြတ် အစီရင်ခံစာ" },
            { "Menu_Sync", "ဒေတာ ချိတ်ဆက်မှု (Sync)" },
            { "Menu_Push", "စစ်ဆေးပြီး Cloud သို့တင်ရန်" },
            { "Menu_Settings", "စနစ် အဆင့်မြင့် ဆက်တင်" },
            { "Menu_ThemeLang", "အသွင်အပြင်နှင့် ဘာသာစကား" },
            { "Menu_Defaults", "လုပ်ငန်းသုံး စံနှုန်းများ" },
            { "Menu_Print", "ပရင်တာနှင့် ဘောက်ချာပုံစံ" },
            { "Menu_Roles", "အကောင့်နှင့် လုပ်ပိုင်ခွင့် (RBAC)" },
            { "Menu_Audit", "လုပ်ဆောင်ချက် မှတ်တမ်း" },
            { "Menu_Backup", "ဒေတာ အရန်သိမ်းဆည်းခြင်း" },
            { "Nav_DataManagement", "အချက်အလက် စီမံခန့်ခွဲမှု" },
            { "Nav_RubberTypes", "ရာဘာအမျိုးအစားများ" },
            { "Nav_PaymentMethods", "ငွေပေးချေမှုပုံစံများ" },
            { "Nav_FarmAccounts", "ခြံပိုင်ရှင်စာရင်းများ" },
            { "Menu_BalanceSummary", "ရရန် / ပေးရန် စာရင်းရှင်းတမ်း" },
            { "Menu_PurchaseList", "ဝယ်ယူမှုစာရင်းများ" },
            { "Menu_BuyerAdvanceOut", "ကုန်သည်/ကုမ္ပဏီထံမှ ကြိုတင်ငွေထုတ်ယူခြင်း" },
            { "Menu_BuyerAdvanceIn", "ကုန်သည်/ကုမ္ပဏီသို့ ကြိုတင်ငွေပြန်လည်ပေးသွင်းခြင်း" },
            { "Menu_WarehouseTransfer", "ဂိုဒေါင်သို့ စတော့ခ်ပြောင်းခြင်း" },
            { "Menu_StockBalance", "စတော့ခ်လက်ကျန်စာရင်း" },
            { "Menu_ExpenseManagement", "အသုံးစရိတ် စီမံခန့်ခွဲမှု" },
            { "Menu_ExpenseList", "နေ့စဉ် အသုံးစရိတ်များ" },
            { "Menu_ExpenseSettings", "အသုံးစရိတ် ဆက်တင်များ" },
            { "Menu_FundTransfer", "ငွေစာရင်း လွှဲပြောင်းမှု" },
            { "Menu_SmokingProcess", "ရော်ဘာမှိုင်းခံလုပ်ငန်းစဉ်" },
            { "Menu_SmokingAnalytics", "မှိုင်းခံခြင်း အလျော့အလေးချိန်နှင့် အစိုဓာတ် မှတ်တမ်း" },

            // --- Dashboard ---
            { "DashboardSubtitle", "ယနေ့ {0}၊ လုပ်ငန်းအခြေအနေများကို ခြုံငုံကြည့်ရှုနိုင်ပါသည်။" },
            { "OfflinePending", "Offline Mode ({0} Pending)" },
            { "TodayPurchaseWet", "ယနေ့ အဝယ်စုစုပေါင်း (အစိုပြား)" },
            { "Pound", "ပေါင်" },
            { "PurchaseIncrease", "မနေ့ကထက် ၁၅% ပိုဝယ်နိုင်သည်" },
            { "RSSProduction", "မှိုင်းခံပြား (RSS) ထုတ်လုပ်မှု" },
            { "Shrinkage", "Shrinkage (အလေအလွင့်) ၁၂%" },
            { "CashBankBalance", "ငွေသားနှင့် ဘဏ် လက်ကျန်" },
            { "Kyat", "ကျပ်" },
            { "TotalKPayCash", "KPay, Cash အားလုံးပေါင်း" },
            { "WarehouseStock", "ဂိုဒေါင် ရော်ဘာလက်ကျန်" },
            { "TotalAllWarehouses", "ဂိုဒေါင်အားလုံး စုစုပေါင်း" },
            { "WeeklyPurchaseTrend", "ရက်သတ္တပတ် အဝယ်နှုန်းထား (အစိုပြား/ပေါင်)" },
            { "QuickActions", "အမြန်လုပ်ဆောင်ချက်များ" },
            { "BuyWetRubber", "အစိုပြား ဝယ်မည်" },
            { "RecordExpense", "အသုံးစရိတ် သွင်းမည်" },
            { "AddNewSupplier", "ဖောက်သည် အသစ်ထည့်မည်" },
            { "ManualSyncBtn", "Manual Sync ပြုလုပ်မည်" },
            { "RecentTransactions", "နောက်ဆုံး လုပ်ဆောင်ခဲ့သော စာရင်းများ" },

            // --- Common/General ---
            { "Voucher", "ဘောက်ချာ" },
            { "NameDescription", "အမည်/အကြောင်းအရာ" },
            { "Amount", "ပမာဏ" },
            { "Status", "အခြေအနေ" },
            { "Cleared", "ရှင်းပြီး" },
            { "Pending", "Pending" },
            { "ClearedKpay", "ရှင်းပြီး (KPay)" },
            { "Alerts", "သတိပေးချက်များ" },
            { "AdvancePaymentAlert", "ခြံရှင် ဦးမြ ကို ကြိုတင်ငွေပေးထားသည်မှာ ၁ လ ပြည့်သွားပါပြီ။" },
            { "LowStockAlert", "ဂိုဒေါင် (က) တွင် RSS ပြားများ သတ်မှတ်ပမာဏထက် လျော့နည်းနေပါသည်။" },
            { "Cancel", "ပယ်ဖျက်မည်" },
            { "Creating", "ဖန်တီးနေပါသည်..." },
            { "Create", "အကောင့်ဖန်တီးမည်" },
            { "GeneralError", "အမှားအယွင်း ဖြစ်ပေါ်သည်: " },
            { "Btn_AddNew", "အသစ်ထည့်မည်" },
            { "Btn_Edit", "ပြင်ဆင်မည်" },
            { "Btn_Delete", "ဖျက်မည်" },
            { "Btn_Add", "အသစ်ထည့်မည်" },
            { "Btn_YesDelete", "ဖျက်မည်" },
            { "Btn_Cancel", "မဖျက်ပါ" },
            { "Btn_Back", "နောက်သို့" },
            { "Btn_Saving", "သိမ်းဆည်းနေပါသည်..." },
            { "Btn_Save", "သိမ်းဆည်းမည်" },
            { "Btn_SaveChanges", "အပြောင်းအလဲများကို သိမ်းမည်" },
            { "Btn_Yes", "ဟုတ်ပါတယ်" },
            { "Msg_Warning", "သတိပေးချက်" },
            { "Msg_DeleteConfirm", "{0} ၏ မှတ်တမ်းကို ဖျက်ပစ်ရန် သေချာပါသလား?" },
            { "Msg_DelSuccess", "မှတ်တမ်းကို အောင်မြင်စွာ ဖျက်ပစ်လိုက်ပါပြီ။" },
            { "Msg_DelError", "ဖျက်သိမ်းရာတွင် အမှားအယွင်းရှိပါသည်။" },
            { "Msg_NetError", "ကွန်ရက်ချိတ်ဆက်မှု အမှားအယွင်း: " },
            { "Msg_LoadError", "ဒေတာရယူရာတွင် အမှားအယွင်းရှိပါသည်: " },
            { "Msg_Success", "ကြိုတင်ငွေ ထုတ်ပေးမှု အောင်မြင်ပါသည်။" },
            { "Msg_Error", "အမှားအယွင်း: " },
            { "Msg_NotFound", "အချက်အလက် ရှာမတွေ့ပါ။" },
            { "Msg_UpdateSuccess", "ပြင်ဆင်မှု အောင်မြင်ပါသည်။" },
            { "Confirm_Title", "အတည်ပြုရန်" },
            { "Confirm_DeleteMessage", "ဤအချက်အလက်ကို ဖျက်ရန် သေချာပါသလား?" },

            // --- Staff Management ---
            { "Staff_AddNew", "ဝန်ထမ်းအကောင့် အသစ်ဖန်တီးရန်" },
            { "Staff_Name", "ဝန်ထမ်းအမည်" },
            { "Staff_Email", "အီးမေးလ် (Email)" },
            { "Staff_Password", "စကားဝှက် (Password)" },
            { "Staff_CreateSuccess", "ဝန်ထမ်းအကောင့် အောင်မြင်စွာ ဖန်တီးပြီးပါပြီ။" },
            { "Staff_CreateError", "အကောင့်ဖန်တီး၍ မရပါ။ " },
            { "Staff_ListTitle", "ဝန်ထမ်းအကောင့်များ စာရင်း" },
            { "Staff_SearchPlaceholder", "အမည် (သို့) အီးမေးလ်ဖြင့် ရှာဖွေရန်..." },
            { "Staff_TableColName", "ဝန်ထမ်းအမည်" },
            { "Staff_TableColEmail", "အီးမေးလ် (Email)" },
            { "Staff_TableColRole", "ရာထူး / အခန်းကဏ္ဍ" },
            { "Staff_DeleteConfirm", " ၏ အကောင့်ကို ဖျက်ပစ်ရန် သေချာပါသလား?" },
            { "Staff_DeleteSuccess", "ဝန်ထမ်းအကောင့်ကို အောင်မြင်စွာ ဖျက်ပစ်လိုက်ပါပြီ။" },
            { "Staff_DeleteError", "ဖျက်သိမ်းရာတွင် အမှားအယွင်းရှိပါသည်။" },
            { "Staff_LoadError", "ဝန်ထမ်းစာရင်း ရယူရာတွင် အမှားအယွင်းရှိပါသည်: " },

            // --- Payment Methods ---
            { "Payment_ListTitle", "ငွေပေးချေမှုပုံစံများ စီမံခန့်ခွဲရန်" },
            { "Payment_SearchPlaceholder", "ငွေပေးချေမှုပုံစံဖြင့် ရှာဖွေရန်..." },
            { "Payment_ColName", "ငွေပေးချေမှု အမည်" },
            { "Payment_ColType", "အမျိုးအစား" },
            { "Payment_ColDetails", "အကောင့်အမည် နှင့် နံပါတ်" },
            { "Payment_ColStatus", "အခြေအနေ" },
            { "Payment_StatusActive", "အသုံးပြုဆဲ" },
            { "Payment_StatusInactive", "ရပ်ဆိုင်းထားသည်" },
            { "Payment_AddTitle", "ငွေပေးချေမှုပုံစံ အသစ်ထည့်ရန်" },
            { "Payment_EditTitle", "ငွေပေးချေမှုပုံစံ ပြင်ဆင်ရန်" },
            { "Payment_NameLabel", "ငွေပေးချေမှု အမည် (ဥပမာ - KBZ Pay)" },
            { "Payment_TypeLabel", "အမျိုးအစား (ဥပမာ - Wallet / Bank)" },
            { "Payment_DetailsLabel", "အကောင့်အမည် နှင့် ဖုန်း/ဘဏ်နံပါတ်" },
            { "Payment_SaveSuccess", "ငွေပေးချေမှုပုံစံကို အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။" },
            { "Payment_DeleteConfirm", "ဤငွေပေးချေမှုပုံစံကို ဖျက်ပစ်ရန် သေချာပါသလား?" },

            // --- Rubber Types ---
            { "Rubber_ListTitle", "ရာဘာအမျိုးအစားများ စီမံခန့်ခွဲရန်" },
            { "Rubber_SearchPlaceholder", "ရာဘာအမျိုးအစားဖြင့် ရှာဖွေရန်..." },
            { "Rubber_ColName", "ရာဘာအမျိုးအမည်" },
            { "Rubber_ColGrade", "အဆင့် (Grade)" },
            { "Rubber_ColDesc", "ဖော်ပြချက်" },
            { "Rubber_AddTitle", "ရာဘာအမျိုးအစား အသစ်ထည့်ရန်" },
            { "Rubber_EditTitle", "ရာဘာအမျိုးအစား ပြင်ဆင်ရန်" },
            { "Rubber_NameLabel", "ရာဘာအမျိုးအမည် (ဥပမာ - RSS-3)" },
            { "Rubber_GradeLabel", "အဆင့် (Grade)" },
            { "Rubber_DescLabel", "ဖော်ပြချက်" },
            { "Rubber_AddButton", "အသစ်ထည့်မည်" },
            { "Rubber_EditButton", "ပြင်ဆင်မည်" },
            { "Rubber_DeleteButton", "ဖျက်မည်" },
            { "Rubber_Cancel", "ပယ်ဖျက်မည်" },
            { "Rubber_Save", "သိမ်းမည်" },
            { "Rubber_Update", "ပြင်ဆင်သိမ်းဆည်းမည်" },
            { "Rubber_SaveSuccess", "ရာဘာအမျိုးအစားကို အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။" },
            { "Rubber_UpdateSuccess", "ရာဘာအမျိုးအစားကို အောင်မြင်စွာ ပြင်ဆင်ပြီးပါပြီ။" },
            { "Rubber_DeleteSuccess", "ရာဘာအမျိုးအစားကို အောင်မြင်စွာ ဖျက်ပစ်လိုက်ပါပြီ။" },
            { "Rubber_DeleteConfirm", "ဤရာဘာအမျိုးအစားကို ဖျက်ပစ်ရန် သေချာပါသလား?" },

            // --- Purchasing ---
            { "Purchase_ListTitle", "ရာဘာအဝယ်ကဏ္ဍ စီမံခန့်ခွဲရန်" },
            { "Purchase_SearchPlaceholder", "ရောင်းချသူ (သို့) ရာဘာအမျိုးအစားဖြင့် ရှာရန်..." },
            { "Purchase_ColSupplier", "ရောင်းချသူအမည်" },
            { "Purchase_ColType", "ရာဘာအမျိုးအစား" },
            { "Purchase_ColWeight", "အလေးချိန်" },
            { "Purchase_ColPrice", "ဈေးနှုန်း (တစ်ယူနစ်)" },
            { "Purchase_ColTotal", "စုစုပေါင်းငွေ" },
            { "Purchase_ColDate", "ရက်စွဲ" },
            { "Purchase_AddButton", "အဝယ်အသစ်စာရင်းသွင်းမည်" },
            { "Purchase_EditButton", "ပြင်ဆင်မည်" },
            { "Purchase_AddTitle", "ရာဘာအဝယ်စာရင်း အသစ်ထည့်ရန်" },
            { "Purchase_EditTitle", "ရာဘာအဝယ်စာရင်း ပြင်ဆင်ရန်" },
            { "Purchase_SupplierLabel", "ရောင်းချသူအမည်" },
            { "Purchase_TypeLabel", "ရာဘာအမျိုးအစား" },
            { "Purchase_WeightLabel", "အလေးချိန်" },
            { "Purchase_PriceLabel", "တစ်ယူနစ်ဈေးနှုန်း" },
            { "Purchase_SaveSuccess", "ရာဘာအဝယ်စာရင်းကို အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။" },
            { "Purchase_UpdateSuccess", "ရာဘာအဝယ်စာရင်းကို အောင်မြင်စွာ ပြင်ဆင်ပြီးပါပြီ။" },
            { "Purchase_DeleteSuccess", "ရာဘာအဝယ်စာရင်းကို အောင်မြင်စွာ ဖျက်ပစ်လိုက်ပါပြီ။" },
            { "Purchase_DeleteConfirm", "ဤရာဘာအဝယ်စာရင်းကို ဖျက်ပစ်ရန် သေချာပါသလား?" },

            // --- Pricing ---
            { "Price_ListTitle", "နေ့စဉ်ပေါက်ဈေး သတ်မှတ်ရန်" },
            { "Price_SearchPlaceholder", "ရာဘာအမျိုးအစားဖြင့် ရှာရန်..." },
            { "Price_ColType", "ရာဘာအမျိုးအစား" },
            { "Price_ColPrice", "တစ်ယူနစ် ပေါက်ဈေး" },
            { "Price_ColDate", "သတ်မှတ်ရက်စွဲ" },
            { "Price_AddButton", "ပေါက်ဈေးအသစ် သတ်မှတ်မည်" },
            { "Price_EditButton", "ဈေးနှုန်းပြင်ဆင်မည်" },
            { "Price_AddTitle", "နေ့စဉ်ပေါက်ဈေး အသစ်ထည့်ရန်" },
            { "Price_EditTitle", "နေ့စဉ်ပေါက်ဈေး ပြင်ဆင်ရန်" },
            { "Price_TypeLabel", "ရာဘာအမျိုးအစား" },
            { "Price_ValueLabel", "တစ်ယူနစ်ပေါက်ဈေး" },
            { "Price_DateLabel", "သတ်မှတ်ရက်စွဲ" },
            { "Price_SaveSuccess", "နေ့စဉ်ပေါက်ဈေးကို အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။" },
            { "Price_UpdateSuccess", "နေ့စဉ်ပေါက်ဈေးကို အောင်မြင်စွာ ပြင်ဆင်ပြီးပါပြီ။" },
            { "Price_DeleteSuccess", "နေ့စဉ်ပေါက်ဈေးကို အောင်မြင်စွာ ဖျက်ပစ်လိုက်ပါပြီ။" },
            { "Price_DeleteConfirm", "ဤပေါက်ဈေးမှတ်တမ်းကို ဖျက်ပစ်ရန် သေချာပါသလား?" },

            // --- Expenses & Incomes ---
            { "Expense_ListTitle", "အသုံးစရိတ်စာရင်းများ" },
            { "Expense_SearchPlaceholder", "ခေါင်းစဉ် သို့မဟုတ် အမျိုးအစားဖြင့် ရှာရန်..." },
            { "Expense_ColTitle", "ခေါင်းစဉ်" },
            { "Expense_ColCategory", "အမျိုးအစား" },
            { "Expense_ColAmount", "ငွေပမာဏ" },
            { "Expense_ColDate", "နေ့စွဲ" },
            { "Expense_ColNote", "မှတ်ချက်" },
            { "Expense_AddButton", "အသုံးစရိတ် အသစ်ထည့်ရန်" },
            { "Expense_EditButton", "ပြင်ဆင်ရန်" },
            { "Expense_AddTitle", "အသုံးစရိတ်အသစ် ထည့်သွင်းခြင်း" },
            { "Expense_EditTitle", "အသုံးစရိတ် ပြင်ဆင်ခြင်း" },
            { "Expense_TitleLabel", "ခေါင်းစဉ်" },
            { "Expense_CategoryLabel", "အမျိုးအစား" },
            { "Expense_AmountLabel", "ငွေပမာဏ" },
            { "Expense_PaymentMethodLabel", "ငွေပေးချေမှု နည်းလမ်း" },
            { "Expense_SaveSuccess", "အသုံးစရိတ်ကို အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။" },
            { "Expense_UpdateSuccess", "အသုံးစရိတ်ကို အောင်မြင်စွာ ပြင်ဆင်ပြီးပါပြီ။" },
            { "Expense_DeleteSuccess", "အသုံးစရိတ်ကို အောင်မြင်စွာ ဖျက်ပြီးပါပြီ။" },
            { "Expense_DeleteConfirm", "ဤအသုံးစရိတ်မှတ်တမ်းကို ဖျက်ပစ်ရန် သေချာပါသလား?" },
            { "Expense_ColPaymentMethod", "ငွေပေးချေမှု နည်းလမ်း" },

            { "Income_ListTitle", "အခြားဝင်ငွေများ စီမံခန့်ခွဲရန်" },
            { "Income_SearchPlaceholder", "အကြောင်းအရာဖြင့် ရှာရန်..." },
            { "Income_ColDesc", "အကြောင်းအရာ" },
            { "Income_ColAmount", "ရရှိငွေ" },
            { "Income_ColDate", "ရက်စွဲ" },
            { "Income_ColNote", "မှတ်ချက်" },
            { "Income_AddButton", "ဝင်ငွေအသစ် ထည့်မည်" },
            { "Income_EditButton", "ပြင်ဆင်မည်" },
            { "Income_AddTitle", "ဝင်ငွေ အသစ်ထည့်ရန်" },
            { "Income_EditTitle", "ဝင်ငွေ ပြင်ဆင်ရန်" },
            { "Income_DescLabel", "အကြောင်းအရာ" },
            { "Income_AmountLabel", "ရရှိငွေပမာဏ" },
            { "Income_SaveSuccess", "ဝင်ငွေကို အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။" },
            { "Income_UpdateSuccess", "ဝင်ငွေကို အောင်မြင်စွာ ပြင်ဆင်ပြီးပါပြီ။" },
            { "Income_DeleteSuccess", "ဝင်ငွေကို အောင်မြင်စွာ ဖျက်ပစ်လိုက်ပါပြီ။" },
            { "Income_DeleteConfirm", "ဤဝင်ငွေမှတ်တမ်းကို ဖျက်ပစ်ရန် သေချာပါသလား?" },
            { "Income_ColPaymentMethod", "ငွေပေးချေမှု နည်းလမ်း" },
            { "Income_PaymentMethodLabel", "ငွေပေးချေမှု နည်းလမ်း" },
            { "Income_Cash", "ငွေသား (Cash)" },

            // --- Expense Settings ---
            { "ExpSetting_Title", "အသုံးစရိတ် အမျိုးအစားနှင့် ခေါင်းစဉ်များ သတ်မှတ်ရန်" },
            { "ExpSetting_TabCategory", "အမျိုးအစားများ" },
            { "ExpSetting_TabTitle", "ခေါင်းစဉ်များ" },
            { "ExpSetting_NameLabel", "အမည် (ဥပမာ - နေ့စဉ်အသုံးစရိတ်၊ ထမင်းဘိုး)" },
            { "ExpSetting_AddBtn", "အသစ်ထည့်ရန်" },
            { "ExpSetting_SaveSuccess", "အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။" },
            { "ExpSetting_DeleteSuccess", "အောင်မြင်စွာ ဖျက်ပြီးပါပြီ။" },
            { "ExpSetting_TypeLabel", "အမျိုးအစား" },
            { "ExpSetting_CategoryOpt", "Category (အမျိုးအစား)" },
            { "ExpSetting_TitleOpt", "Title (ခေါင်းစဉ်)" },
            { "ExpSetting_ParentCategoryLabel", "မည်သည့် အမျိုးအစားအောက်တွင် ထည့်မည်နည်း" },
            { "ExpSetting_SearchPlaceholder", "အမည်ဖြင့် ရှာရန်..." },
            { "ExpSetting_ColType", "အမျိုးအစား" },
            { "ExpSetting_ColName", "အမည်" },
            { "ExpSetting_ColParentCategory", "အဓိက အမျိုးအစား" },

            // --- Logistics (Trucks & Expenses) ---
            { "Truck_ListTitle", "ကုန်တင်ကားများ စီမံခန့်ခွဲရန်" },
            { "Truck_SearchPlaceholder", "ကားနံပါတ် (သို့) ယာဉ်မောင်းဖြင့် ရှာရန်..." },
            { "Truck_ColNumber", "ကားနံပါတ်" },
            { "Truck_ColDriver", "ယာဉ်မောင်းအမည်" },
            { "Truck_ColStatus", "အခြေအနေ" },
            { "Truck_ColCapacity", "တင်နိုင်သည့် ဝန် (ကီလို)" },
            { "Truck_AddButton", "ကားအသစ် ထည့်မည်" },
            { "Truck_EditButton", "ပြင်ဆင်မည်" },
            { "Truck_AddTitle", "ကားအသစ် ထည့်သွင်းရန်" },
            { "Truck_EditTitle", "ကားအချက်အလက် ပြင်ဆင်ရန်" },
            { "Truck_NumberLabel", "ကားနံပါတ် (ဥပမာ - 8A-1234)" },
            { "Truck_DriverLabel", "ယာဉ်မောင်းအမည်" },
            { "Truck_StatusLabel", "အခြေအနေ" },
            { "Truck_CapacityLabel", "တင်နိုင်သည့် ဝန် (ကီလို)" },
            { "Truck_SaveSuccess", "ကုန်တင်ကားစာရင်းကို အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။" },
            { "Truck_UpdateSuccess", "ကုန်တင်ကားစာရင်းကို အောင်မြင်စွာ ပြင်ဆင်ပြီးပါပြီ။" },
            { "Truck_DeleteSuccess", "ကုန်တင်ကားစာရင်းကို အောင်မြင်စွာ ဖျက်ပစ်လိုက်ပါပြီ။" },
            { "Truck_DeleteConfirm", "ဤကုန်တင်ကားမှတ်တမ်းကို ဖျက်ပစ်ရန် သေချာပါသလား?" },

            { "TruckExp_ListTitle", "ကား ဆီဖိုးနှင့် ပြုပြင်စရိတ်များ" },
            { "TruckExp_SearchPlaceholder", "ကားနံပါတ် (သို့) အမျိုးအစားဖြင့် ရှာရန်..." },
            { "TruckExp_ColTruck", "ကားနံပါတ်" },
            { "TruckExp_ColType", "အမျိုးအစား" },
            { "TruckExp_ColAmount", "ကျသင့်ငွေ" },
            { "TruckExp_ColPayment", "ငွေပေးချေမှု နည်းလမ်း" },
            { "TruckExp_ColDate", "ရက်စွဲ" },
            { "TruckExp_ColNote", "မှတ်ချက်" },
            { "TruckExp_AddButton", "စရိတ်အသစ် ထည့်မည်" },
            { "TruckExp_EditButton", "ပြင်ဆင်မည်" },
            { "TruckExp_AddTitle", "ကားစရိတ် အသစ်ထည့်ရန်" },
            { "TruckExp_EditTitle", "ကားစရိတ် ပြင်ဆင်ရန်" },
            { "TruckExp_TruckLabel", "ကားနံပါတ်" },
            { "TruckExp_TypeLabel", "အမျိုးအစား (ဆီဖိုး / ပြုပြင်စရိတ်)" },
            { "TruckExp_Fuel", "ဆီဖိုး" },
            { "TruckExp_Maintenance", "ပြုပြင်စရိတ်" },
            { "TruckExp_SaveSuccess", "ကားစရိတ်ကို အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။" },
            { "TruckExp_UpdateSuccess", "ကားစရိတ်ကို အောင်မြင်စွာ ပြင်ဆင်ပြီးပါပြီ။" },
            { "TruckExp_DeleteSuccess", "ကားစရိတ်ကို အောင်မြင်စွာ ဖျက်ပစ်လိုက်ပါပြီ။" },
            { "TruckExp_DeleteConfirm", "ဤကားစရိတ်မှတ်တမ်းကို ဖျက်ပစ်ရန် သေချာပါသလား?" },

            // --- Employee Management ---
            { "Emp_ListTitle", "ဝန်ထမ်းများ စီမံခန့်ခွဲရန်" },
            { "Emp_SearchPlaceholder", "အမည် (သို့) ရာထူးဖြင့် ရှာရန်..." },
            { "Emp_ColName", "အမည်အပြည့်အစုံ" },
            { "Emp_ColPosition", "ရာထူး" },
            { "Emp_ColSalary", "လစာ" },
            { "Emp_ColPhone", "ဖုန်းနံပါတ်" },
            { "Emp_AddButton", "ဝန်ထမ်းအသစ် ထည့်မည်" },
            { "Emp_EditButton", "ပြင်ဆင်မည်" },
            { "Emp_AddTitle", "ဝန်ထမ်း အသစ်ထည့်ရန်" },
            { "Emp_EditTitle", "ဝန်ထမ်းအချက်အလက် ပြင်ဆင်ရန်" },
            { "Emp_NameLabel", "အမည်အပြည့်အစုံ" },
            { "Emp_PositionLabel", "ရာထူး" },
            { "Emp_SalaryLabel", "လစာ" },
            { "Emp_PhoneLabel", "ဖုန်းနံပါတ်" },
            { "Emp_AddressLabel", "နေရပ်လိပ်စာ" },
            { "Emp_DateLabel", "ခန့်အပ်သည့်ရက်စွဲ" },
            { "Emp_StatusLabel", "အခြေအနေ" },
            { "Emp_Profile", "အသေးစိတ်" },
            { "Emp_SaveSuccess", "ဝန်ထမ်းစာရင်းကို အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။" },
            { "Emp_UpdateSuccess", "ဝန်ထမ်းစာရင်းကို အောင်မြင်စွာ ပြင်ဆင်ပြီးပါပြီ။" },
            { "Emp_DeleteSuccess", "ဝန်ထမ်းစာရင်းကို အောင်မြင်စွာ ဖျက်ပစ်လိုက်ပါပြီ။" },
            { "Emp_DeleteConfirm", "ဤဝန်ထမ်းမှတ်တမ်းကို ဖျက်ပစ်ရန် သေချာပါသလား?" },

            // --- Warehouse Management ---
            { "Wh_ListTitle", "ဂိုဒေါင်များ စီမံခန့်ခွဲရန်" },
            { "Wh_SearchPlaceholder", "ဂိုဒေါင်အမည် (သို့) တည်နေရာဖြင့် ရှာရန်..." },
            { "Wh_ColName", "ဂိုဒေါင်အမည်" },
            { "Wh_ColLocation", "တည်နေရာ" },
            { "Wh_ColManager", "တာဝန်ခံ" },
            { "Wh_ColPhone", "ဖုန်းနံပါတ်" },
            { "Wh_ColCapacity", "ဆံ့ဝင်မှုပမာဏ" },
            { "Wh_AddButton", "ဂိုဒေါင်အသစ် ထည့်မည်" },
            { "Wh_EditButton", "ပြင်ဆင်မည်" },
            { "Wh_AddTitle", "ဂိုဒေါင် အသစ်ထည့်ရန်" },
            { "Wh_EditTitle", "ဂိုဒေါင်အချက်အလက် ပြင်ဆင်ရန်" },
            { "Wh_NameLabel", "ဂိုဒေါင်အမည်" },
            { "Wh_LocationLabel", "တည်နေရာ / လိပ်စာ" },
            { "Wh_ManagerLabel", "တာဝန်ခံအမည်" },
            { "Wh_PhoneLabel", "ဖုန်းနံပါတ်" },
            { "Wh_CapacityLabel", "ဆံ့ဝင်မှုပမာဏ / ဖော်ပြချက်" },
            { "Wh_SaveSuccess", "ဂိုဒေါင်စာရင်းကို အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။" },
            { "Wh_UpdateSuccess", "ဂိုဒေါင်စာရင်းကို အောင်မြင်စွာ ပြင်ဆင်ပြီးပါပြီ။" },
            { "Wh_DeleteSuccess", "ဂိုဒေါင်စာရင်းကို အောင်မြင်စွာ ဖျက်ပစ်လိုက်ပါပြီ။" },
            { "Wh_DeleteConfirm", "ဤဂိုဒေါင်မှတ်တမ်းကို ဖျက်ပစ်ရန် သေချာပါသလား?" },

            // --- Daily Notes ---
            { "Note_ListTitle", "နေ့စဉ်မှတ်တမ်းများနှင့် လုပ်ဆောင်ချက်များ" },
            { "Note_SearchPlaceholder", "ခေါင်းစဉ် (သို့) အကြောင်းအရာဖြင့် ရှာရန်..." },
            { "Note_ColTitle", "ခေါင်းစဉ်" },
            { "Note_ColContent", "အကြောင်းအရာ" },
            { "Note_ColDate", "ရက်စွဲ" },
            { "Note_AddButton", "မှတ်တမ်းအသစ် ထည့်မည်" },
            { "Note_EditButton", "ပြင်ဆင်မည်" },
            { "Note_AddTitle", "မှတ်တမ်း အသစ်ထည့်ရန်" },
            { "Note_EditTitle", "မှတ်တမ်း ပြင်ဆင်ရန်" },
            { "Note_TitleLabel", "မှတ်တမ်း ခေါင်းစဉ်" },
            { "Note_ContentLabel", "အကြောင်းအရာ / အသေးစိတ်" },
            { "Note_DateLabel", "ရက်စွဲ" },
            { "Note_SaveSuccess", "မှတ်တမ်းကို အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။" },
            { "Note_UpdateSuccess", "မှတ်တမ်းကို အောင်မြင်စွာ ပြင်ဆင်ပြီးပါပြီ။" },
            { "Note_DeleteSuccess", "မှတ်တမ်းကို အောင်မြင်စွာ ဖျက်ပစ်လိုက်ပါပြီ။" },
            { "Note_DeleteConfirm", "ဤမှတ်တမ်းကို ဖျက်ပစ်ရန် သေချာပါသလား?" },

            // --- Rubber Sales ---
            { "Sale_ListTitle", "ရာဘာအရောင်းစာရင်း" },
            { "Sale_ColVoucher", "ဘောင်ချာနံပါတ်" },
            { "Sale_ColBuyer", "ဝယ်သူအမည်" },
            { "Sale_ColWarehouse", "ဂိုဒေါင်" },
            { "Sale_ColType", "ရာဘာအမျိုးအစား" },
            { "Sale_ColWeight", "အလေးချိန်" },
            { "Sale_ColPrice", "ဈေးနှုန်း" },
            { "Sale_ColTotal", "စုစုပေါင်းငွေ" },
            { "Sale_ColPayment", "ငွေပေးချေမှု နည်းလမ်း" },
            { "Sale_ColDate", "ရက်စွဲ" },
            { "Sale_ColNote", "မှတ်ချက်" },
            { "Sale_AddButton", "အသစ်ထည့်မည်" },
            { "Sale_EditButton", "ပြင်ဆင်မည်" },
            { "Sale_AddTitle", "ရာဘာအရောင်း ဘောင်ချာအသစ် ထည့်သွင်းရန်" },
            { "Sale_EditTitle", "ရာဘာအရောင်း ဘောင်ချာ ပြင်ဆင်ရန်" },
            { "Sale_InvoiceLabel", "ဘောင်ချာနံပါတ်" },
            { "Sale_CustomerLabel", "ဝယ်ယူသူ / ကုမ္ပဏီအမည်" },
            { "Sale_WarehouseLabel", "ထုတ်ယူမည့် ဂိုဒေါင်" },
            { "Sale_TypeLabel", "ရာဘာအမျိုးအစား" },
            { "Sale_WeightLabel", "အလေးချိန် (ကီလို)" },
            { "Sale_PriceLabel", "တစ်ကီလိုဈေးနှုန်း" },
            { "Sale_TotalLabel", "စုစုပေါင်းကျသင့်ငွေ" },
            { "Sale_SaveSuccess", "အရောင်းဘောင်ချာကို အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။" },
            { "Sale_UpdateSuccess", "အရောင်းဘောင်ချာကို အောင်မြင်စွာ ပြင်ဆင်ပြီးပါပြီ။" },
            { "Sale_DeleteSuccess", "အရောင်းစာရင်းကို အောင်မြင်စွာ ဖျက်ပြီးပါပြီ။" },
            { "Sale_DeleteConfirm", "ဤအရောင်းစာရင်းကို ဖျက်ရန် သေချာပါသလား?" },
            { "Sale_Title", "ရာဘာအရောင်း ဘောင်ချာ" },
            { "Sale_SourceType", "ပစ္စည်းထုတ်ယူမည့်နေရာ" },
            { "Sale_SelectSource", "စတော့ခ်ရင်းမြစ် ရွေးချယ်ပါ" },
            { "Sale_AvailableQty", "လက်ရှိရှိနေသော ပမာဏ" },
            { "Sale_Buyer", "ကုန်သည်/ကုမ္ပဏီ ရွေးချယ်ပါ" },
            { "Sale_ActualPaid", "ရရှိငွေပမာဏ" },
            { "Sale_Wallet", "ငွေလက်ခံမည့်အကောင့် (Wallet)" },
            { "Sale_SaveButton", "အရောင်းအတည်ပြုမည်" },
            { "Sale_QtyWarningTitle", "ပမာဏ ကျော်လွန်နေပါသည်" },
            { "Sale_QtyWarningMsg", "ထည့်သွင်းထားသော အလေးချိန်သည် လက်ရှိရှိနေသည့် ပမာဏထက် ပိုနေပါသည်။ လက်ရှိပမာဏအတိုင်း ရောင်းချမည်မှာ သေချာပါသလား?" },
            { "Sale_SearchPlaceholder", "ဘောင်ချာ၊ ဝယ်သူဖြင့် ရှာရန်..." },

            // --- Reports, Stocks & Processing ---
            { "Report_Title", "ဘဏ္ဍာရေး အနှစ်ချုပ် အစီရင်ခံစာ" },
            { "Report_Generate", "အစီရင်ခံစာ ထုတ်ယူရန်" },
            { "Stock_Title", "ဂိုဒေါင်လက်ကျန်စာရင်း" },
            { "Stock_ColWarehouse", "ဂိုဒေါင်" },
            { "Stock_ColType", "ရာဘာအမျိုးအစား" },
            { "Stock_ColBalance", "လက်ကျန် (ကီလို)" },

            { "Smoking_Title", "ရာဘာမှိုင်းခံခြင်း လုပ်ငန်းစဉ်" },
            { "Smoking_NewBatch", "မှိုင်းခံအစုအဝေး အသစ်ထည့်ရန်" },
            { "Smoking_BatchNo", "အမှတ်စဉ် (Batch No)" },
            { "Smoking_Status", "အခြေအနေ" },
            { "Smoking_Warehouse", "ဂိုဒေါင်" },
            { "Smoking_Input", "ထည့်ကုန်ကြမ်း (အမျိုးအစား / ပမာဏ)" },
            { "Smoking_Output", "ထွက်ကုန်အခြောက် (အမျိုးအစား / ပမာဏ)" },
            { "Smoking_Shrinkage", "အလေးချိန်လျော့ကျမှု" },
            { "Smoking_Dates", "ရက်စွဲများ" },

            // --- Accounts & Contacts ---
            { "Accounts_Title", "ခြံပိုင်ရှင်စာရင်းများ" },
            { "Supplier_Name", "ခြံပိုင်ရှင်အမည်" },
            { "Total_Purchased", "ဝယ်ယူထားသည့်စုစုပေါင်း" },
            { "Total_Paid", "ပေးချေပြီးစုစုပေါင်း" },
            { "Balance_Due", "ကျန်ငွေ" },
            { "Amount_Paid", "ပေးချေငွေ" },
            { "Payment_Method", "ငွေပေးချေမှုနည်းလမ်း" },
            { "Cash", "ငွေသား" },
            { "Bank_Transfer", "ဘဏ်မှလွှဲပြောင်းခြင်း" },
            { "ContactsTitle", "ခြံရှင်နှင့် ကုန်သည်များ စာရင်း" },
            { "SearchContact", "အမည် (သို့) ဖုန်းနံပါတ်ဖြင့် ရှာဖွေရန်..." },
            { "Col_Name", "အမည်" },
            { "Col_Phone", "ဖုန်းနံပါတ်" },
            { "Col_Type", "အမျိုးအစား" },
            { "Col_Advance", "ကြိုပေးငွေ/အကြွေး (ကျပ်)" },

            { "Title_AddContact", "အဆက်အသွယ် အသစ်ထည့်ရန်" },
            { "Lbl_Name", "အမည် / ကုမ္ပဏီအမည်" },
            { "Err_NameRequired", "အမည် ထည့်ရန်လိုအပ်ပါသည်" },
            { "Lbl_Phone", "ဖုန်းနံပါတ်" },
            { "Lbl_ContactType", "အမျိုးအစား" },
            { "Opt_Supplier", "ခြံရှင်/ပွဲစား" },
            { "Opt_Buyer", "ဝယ်ယူသူ/ဒိုင်" },
            { "Opt_General", "အထွေထွေ" },
            { "Lbl_BankInfo", "ဘဏ် / KPay အချက်အလက်" },
            { "Lbl_Address", "နေရပ်လိပ်စာ" },
            { "Title_EditContact", "အဆက်အသွယ် ပြင်ဆင်ရန်" },
            { "Filter_All", "အားလုံး" },
            { "Filter_Suppliers", "ခြံရှင်/ပွဲစား" },
            { "Filter_Buyers", "ဝယ်ယူသူ/ဒိုင်" },
            { "Filter_General", "အထွေထွေ" },
            { "Title_AdvanceOut", "ခြံရှင်သို့ ကြိုတင်ငွေထုတ်ပေးခြင်း" },
            { "Lbl_SelectSupplier", "ခြံရှင်ရွေးပါ" },
            { "Lbl_Amount", "ထုတ်ပေးမည့် ငွေပမာဏ" },
            { "Lbl_Note", "မှတ်ချက် (အကြောင်းပြချက်)" },
            { "Btn_PayAdvance", "ငွေထုတ်ပေးမည်" },
            { "Title_AdvanceIn", "ခြံရှင်ထံမှ ကြိုတင်ငွေပြန်လက်ခံခြင်း" },
            { "Lbl_CurrentAdvance", "လက်ရှိကြိုတင်ငွေ" },
            { "Lbl_SelectWallet", "ငွေလက်ခံမည့်အကောင့်" },
            { "Btn_ReceiveAdvance", "ကြိုတင်ငွေလက်ခံမည်" },
            { "Msg_WalletUpdateError", "Wallet သို့ ငွေပေါင်းထည့်ရန် မအောင်မြင်ပါ: " },
            { "Title_BalanceSummary", "ရရန် / ပေးရန် ငွေစာရင်းရှင်းတမ်း" },
            { "Card_TotalAdvanceOut", "စုစုပေါင်း ထုတ်ပေးထားသော ကြိုတင်ငွေ " },
            { "Card_TotalReceivable", "စုစုပေါင်း ရရန်ရှိငွေ" },
            { "Tab_Suppliers", "ခြံရှင်များ" },
            { "Tab_Buyers", "ကုန်သည်များ" },
            { "Tab_AllContacts", "အားလုံး" },
            { "Placeholder_Search", "Search by name or phone..." },
            { "Th_Name", "အမည်" },
            { "Th_Phone", "ဖုန်း" },
            { "Th_Type", "အမျိုးအစား" },
            { "Th_AdvanceBalance", "ကြိုတင်ငွေ လက်ကျန်" },
            { "Th_ReceivableBalance", "ရရန်ရှိငွေ လက်ကျန်" },

            // --- Settings & Buying ---
            { "Settings_Title", "လုပ်ငန်းသုံး အချက်အလက်နှင့် သတ်မှတ်ချက်များ" },
            { "Settings_WeightUnit", "အဓိက အလေးချိန်ယူနစ်" },
            { "Settings_ServiceCost", "ပုံသေ ဝန်ဆောင်မှုစရိတ်" },
            { "Settings_Deduction", "ပုံသေ အလျော့ရာခိုင်နှုန်း (%)" },
            { "Settings_Currency", "ငွေကြေးအမျိုးအစား" },
            { "Settings_AutoAdvance", "ကြိုတင်ငွေ အလိုအလျောက် ဖြတ်တောက်ရန်" },
            { "Settings_SaveSuccess", "သတ်မှတ်ချက်များ အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။" },
            { "Settings_SaveButton", "သိမ်းဆည်းမည်" },
            { "Settings_UpdateButton", "ပြင်ဆင်မည်" },
            { "Settings_DeleteButton", "ဖျက်မည်" },
            { "Settings_DeleteConfirm", "ဤသတ်မှတ်ချက်များကို ဖျက်ရန် သေချာပါသလား။" },
            { "Settings_DeleteSuccess", "သတ်မှတ်ချက်များ အောင်မြင်စွာ ဖျက်ပြီးပါပြီ။" },

            { "Buy_Title", "ရာဘာဝယ်ယူခြင်း" },
            { "Buy_Farmer", "ခြံရှင်အမည်" },
            { "Buy_RubberType", "ရာဘာအမျိုးအစား" },
            { "Buy_BasePrice", "ပေါက်ဈေး" },
            { "Buy_ServiceCost", "ဝန်ဆောင်မှုကုန်ကျစရိတ်" },
            { "Buy_DeductionPct", "အလျော့ရာခိုင်နှုန်း % (0-30)" },
            { "Buy_FinalPrice", "ဝယ်ယူမည့်ဈေးနှုန်း" },
            { "Buy_Weight", "အလေးချိန်" },
            { "Buy_TotalAmount", "ကျသင့်ငွေ" },
            { "Buy_Advance", "ကြိုတင်ထုတ်ယူထားငွေ" },
            { "Buy_NetPayola", "အသားတင်ပေးရမည့်ငွေ" },
            { "Buy_ActualPaid", "အမှန်တကယ်ပေးချေသည့်ငွေ" },
            { "Buy_SaveSuccess", "ရာဘာဝယ်ယူမှု အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။" },
            { "Buy_SaveButton", "ဝယ်ယူမှုကို အတည်ပြုမည်" },

            { "Title_WarehouseTransfer", "ဂိုဒေါင်သို့ စတော့ခ်ပြောင်းထည့်ခြင်း" },
            { "Lbl_SelectWarehouse", "ဂိုဒေါင်ရွေးချယ်ပါ" },
            { "Btn_TransferToWarehouse", "ဂိုဒေါင်သို့ အသွင်ပြောင်းမည်" },
            { "Msg_TransferSuccess", "ဂိုဒေါင်သို့ Batch အလိုက် အောင်မြင်စွာ ပြောင်းရွှေ့ပြီးပါပြီ။" },
            { "Msg_SelectStockWarning", "ကျေးဇူးပြု၍ ပြောင်းရွှေ့မည့် စတော့ခ်များကို ရွေးချယ်ပါ။" },

            { "Title_StockBalance", "စတော့ခ်လက်ကျန် အနှစ်ချုပ်" },
            { "Tab_Warehouse", "ဂိုဒေါင်စတော့ခ်များ" },
            { "Tab_TempStock", "ယာယီစတော့ခ်များ (Pending)" },
            { "Tab_TruckStock", "ကားစတော့ခ်များ (Active)" },
            { "Th_WarehouseName", "ဂိုဒေါင်အမည်" },
            { "Th_Supplier", "ခြံရှင်အမည်" },
            { "Th_TruckNumber", "ကားအမှတ်" },
            { "Th_RubberType", "ရာဘာအမျိုးအစား" },
            { "Th_Quantity", "ပမာဏ / အလေးချိန်" },

            { "Transfer_ListTitle", "ငွေလွှဲပြောင်းမှု မှတ်တမ်းများ" },
            { "Transfer_SearchPlaceholder", "အကောင့်အမည်ဖြင့် ရှာရန်..." },
            { "Transfer_ColFrom", "လွှဲထွက်သည့်အကောင့်" },
            { "Transfer_ColTo", "ဝင်ရောက်သည့်အကောင့်" },
            { "Transfer_ColAmount", "ငွေပမာဏ" },
            { "Transfer_ColDate", "နေ့စွဲ" },
            { "Transfer_ColNote", "မှတ်ချက်" },
            { "Transfer_AddButton", "ငွေအသစ် လွှဲမည်" },
            { "Transfer_DeleteButton", "ဖျက်ရန်" },
            { "Transfer_AddTitle", "အကောင့်များကြား ငွေလွှဲပြောင်းခြင်း" },
            { "Transfer_DeleteSuccess", "ငွေလွှဲမှတ်တမ်းကို အောင်မြင်စွာ ဖျက်ပြီးပါပြီ။" },
            { "Transfer_FromLabel", "ငွေလွှဲထွက်မည့်အကောင့် (From)" },
            { "Transfer_ToLabel", "ငွေလက်ခံမည့်အကောင့် (To)" },
            { "Transfer_AmountLabel", "လွှဲပြောင်းမည့် ငွေပမာဏ" },
            { "Transfer_DateLabel", "နေ့စွဲ" },
            { "Transfer_NoteLabel", "မှတ်ချက်" },
            { "Transfer_SaveSuccess", "ငွေကြေးလွှဲပြောင်းမှု အောင်မြင်ပါသည်။" },
            { "Transfer_SameWalletError", "ငွေလွှဲသည့်အကောင့်နှင့် လက်ခံသည့်အကောင့် တူနေ၍မရပါ။" },
            { "Transfer_InsufficientBalance", "ငွေလွှဲမည့်အကောင့်တွင် လက်ကျန်ငွေ မလုံလောက်ပါ။" },

            { "Smoking_ListTitle", "မှိုင်းခံဖို အသုတ်များ စာရင်း" },
            { "Smoking_SearchPlaceholder", "ဘက်ချ်နံပါတ်ဖြင့် ရှာရန်..." },
            { "Smoking_ColBatchNo", "ဘက်ချ်နံပါတ် (Batch No)" },
            { "Smoking_ColStartDate", "စတင်ရက်" },
            { "Smoking_ColEndDate", "ပြီးဆုံးရက်" },
            { "Smoking_ColStatus", "အခြေအနေ" },
            { "Smoking_ColInput", "စုစုပေါင်းထည့်သွင်းမှု (ပေါင်)" },
            { "Smoking_ColOutput", "စုစုပေါင်းထွက်ရှိမှု (ပေါင်)" },
            { "Smoking_ColLoss", "လျော့သွားသည်" },
            { "Smoking_AddButton", "မှိုင်းခံဖို အသုတ်အသစ်ဖွင့်မည်" },
            { "Smoking_CompleteButton", "မှိုင်းခံပြီးစီးကြောင်း အတည်ပြုမည်" },
            { "Smoking_AddTitle", "မှိုင်းခံဖို အသုတ်အသစ် တည်ဆောက်ခြင်း" },
            { "Smoking_CompleteTitle", "မှိုင်းခံပြီးစီးမှုနှင့် Grade သတ်မှတ်ခြင်း" },
            { "Smoking_SupplierLabel", "ခြံရှင် / ပံ့ပိုးသူ (Supplier)" },
            { "Smoking_InputWeightLabel", "ထည့်သွင်းသည့် အလေးချိန် (ပေါင်)" },
            { "Smoking_OutputWeightLabel", "မှိုင်းခံပြီး အသားတင် အလေးချိန် (ပေါင်)" },
            { "Smoking_SaveSuccess", "မှိုင်းခံဖို အသုတ်ကို အောင်မြင်စွာ ဖန်တီးပြီးပါပြီ။" },
            { "Smoking_CompleteSuccess", "မှိုင်းခံခြင်း ပြီးစီးပြီး စာရင်းများ အောင်မြင်စွာ အပ်ဒိတ်ဖြစ်သွားပါပြီ။" },
            { "Th_Source", "ရင်းမြစ် (Source)" },
            { "Th_SupplierOrVehicle", "ခြံရှင် / ကားအမှတ်" },
            { "Th_Weight", "အလေးချိန် / ပမာဏ" },
            { "Th_Moisture", "အစိုဓာတ် %" },
            { "Smoking_TargetWarehouse", "ကုန်ချောလက်ခံမည့် ဂိုဒေါင်ရွေးရန်" },
            { "Smoking_ItemAllocationTitle", "Batch တစ်ခုချင်းစီ၏ ထွက်ရှိမှု၊ Grade၊ လက်ကျန်နှင့် အလျော့အလေးချိန်များ" },
            { "Smoking_GradeLabel", "ကုန်ချော Grade သတ်မှတ်ရန်" },
            { "Smoking_RemainingLabel", "ထပ်မှိုင်းခံရန် လက်ကျန် (lbs)" },
            { "Title_SmokingAnalytics", "မှိုင်းခံခြင်း အလျော့အလေးချိန်နှင့် အစိုဓာတ် မှတ်တမ်း" },
            { "Card_TotalInput", "စုစုပေါင်း သွင်းအား (Input)" },
            { "Card_TotalOutput", "စုစုပေါင်း ကုန်ချော (Output)" },
            { "Card_TotalLoss", "စုစုပေါင်း အလျော့ (Total Loss)" },
            { "Card_AvgMoisture", "ပျမ်းမျှ အစိုဓာတ် (Avg Moisture)" },
            { "Th_BatchNo", "Batch နံပါတ်" },
            { "Th_StartDate", "စတင်ရက်" },
            { "Th_EndDate", "ပြီးဆုံးရက်" },
            { "Th_InputWeight", "သွင်းအား (ပေါင်)" },
            { "Th_OutputWeight", "ကုန်ချော (ပေါင်)" },
            { "Th_LossWeight", "လျော့သွားသည် (ပေါင်)" },
            { "Th_LossPercent", "လျော့ကျမှု %" },
            { "Th_MoisturePercent", "အစိုဓာတ် %" }
        };
    }
}